apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-data
        env:
          - name: WORDPRESS_DB_HOST
            value: service-cluster-ip-mysql:3306
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
        ports:
        - containerPort: 80
      volumes:
      - name: wordpress-data
        hostPath:
          # chemin du dossier sur l'hôte
          path: /data
          # ce champ est optionnel
          type: Directory
